from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from cyclopts import Parameter


@Parameter(name="*")
@dataclass
class FormatterConfig:
    input: Path = Path("datasets/yelp/cleaned_kg_51.json")
    "Input JSON file containing cleaned KG data"

    output_dir: Path = Path("output")
    "Output directory for generated files (relation_list.txt, entity_list.txt, kg_final.txt)"

    # Merge mode options
    merge_mode: bool = False
    "Enable merge mode to combine base KG with supplement KG"

    base_kg_path: Optional[Path] = None
    "Path to base KG file with empty triplets (for merge mode)"

    supplement_kg_path: Optional[Path] = None
    "Path to supplement KG file generated by EDC (for merge mode)"

    merged_output: Path = Path("output/merged_kg.json")
    "Output path for merged complete KG (for merge mode)"

    verbose: bool = False
    "Enable verbose logging"
